#!/bin/sh
# 16:9 1240K
#ts_900k file_path video_code
ffmpeg  -i $1 -f mpegts -codec:a libfaac -ar 32000 -ab 48k -codec:v libx264 -b:v 900k -flags +loop+mv4 -cmp 256 -partitions +parti4x4+partp8x8+partb8x8 -subq 7 -trellis 1 -refs 5 -coder 0 -me_range 16 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -bt 900k -maxrate 900k -bufsize 900k -rc_eq 'blurCplx^(1-qComp)' -qcomp 0.6 -qmin 10 -qmax 51 -qdiff 4 -level 30 -r 30 -g 90 -async 2 -f ssegment -segment_list_flags +live -segment_time 10 -segment_list $2_900000.m3u8 $2_900k_%03d.ts
