#!/bin/sh
# 16:9 150K
#en_16t9_150k file_path video_code
ffmpeg -i $1 -f mpegts -acodec libfaac -ar 32000 -ab 48k -s 400x224 -vcodec libx264 -b:v 110k -flags +loop+mv4 -cmp 256 -partitions +parti4x4+partp8x8+partb8x8 -subq 7 -trellis 1 -refs 5 -coder 0 -me_range 16 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -bt 110k -maxrate 110k -bufsize 110k -rc_eq 'blurCplx^(1-qComp)' -qcomp 0.6 -qmin 10 -qmax 51 -qdiff 4 -level 30 -aspect 16:9 -r 10 -g 30 -async 2 $2_16t9_150k.ts
 
segmenter -i $2_16t9_150k.ts -d 10 -o $2_16t9_150k -x $2_16t9_158000.m3u8

rm -f $2_16t9_150k.ts
