#!/bin/sh
# 16:9 1240K
#en_16t9_1240k file_path video_code
ffmpeg  -i $1 -f mpegts -acodec libfaac -ar 32000 -ab 48k -s 640x360 -vcodec libx264 -b:v 1200k -flags +loop+mv4 -cmp 256 -partitions +parti4x4+partp8x8+partb8x8 -subq 7 -trellis 1 -refs 5 -coder 0 -me_range 16 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -bt 1200k -maxrate 1200k -bufsize 1200k -rc_eq 'blurCplx^(1-qComp)' -qcomp 0.6 -qmin 10 -qmax 51 -qdiff 4 -level 30 -aspect 16:9 -r 30 -g 90 -async 2 $2_16t9_1240k.ts

segmenter -i $2_16t9_1240k.ts -d 10 -o $2_16t9_1240k -x $2_16t9_1248000.m3u8

rm -f $2_16t9_1240k.ts
