#!/bin/sh
# 4:3 640K
#en_4t3_640k file_path video_code
ffmpeg -i $1 -f mpegts -acodec libfaac -ar 32000 -ab 48k -s 640x480 -vcodec libx264 -b:v 600k -flags +loop+mv4 -cmp 256 -partitions +parti4x4+partp8x8+partb8x8 -subq 7 -trellis 1 -refs 5 -coder 0 -me_range 16 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -bt 600k -maxrate 600k -bufsize 600k -rc_eq 'blurCplx^(1-qComp)' -qcomp 0.6 -qmin 10 -qmax 51 -qdiff 4 -level 30 -aspect 4:3 -r 30 -g 90 -async 2 $2_4t3_640k.ts

segmenter -i $2_4t3_640k.ts -d 10 -o $2_4t3_640k -x $2_4t3_648000.m3u8

rm -f $2_4t3_640k.ts
